# Copyright (C), UNIGINE. All rights reserved.


set(UNIGINE_VERSION_MAJOR       2)
set(UNIGINE_VERSION_MINOR       14)
set(UNIGINE_VERSION_PATCH       1)
set(UNIGINE_VERSION_REVISION    0)
set(UNIGINE_VERSION             "${UNIGINE_VERSION_MAJOR}.${UNIGINE_VERSION_MINOR}.${UNIGINE_VERSION_PATCH}.${UNIGINE_VERSION_REVISION}")
